---
title: " Welcome to Change2Twin!"
---

<p class="lead">Digital Twins are virtual representations of real-world products and systems. The concept of Digital Twins is currently recognized as one of the big game-changers for the manufacturing industry
allowing companies to significantly increase their global competitiveness.</p>
The EFFRA’s Factories of the future
multi-annual [roadmap for Horizon 2020](docs/factories_of_the_future_2020_roadmap.pdf) presents “Modelling, simulation and forecasting methods and tools” as one
of the key technologies and enablers. This importance is highlighted even more in the roadmap for Horizon Europe
,
where digital twinning is highlighted as the enabler with the highest contribution to all of the key priorities of
European manufacturing.

**Change2Twin** focuses on smart modelling, simulation, and
optimisation for digital twins, with the following main ambition:

<blockquote class="blockquote">To ensure that 100% of manufacturing companies in Europe have access to 100% of technologies needed to
deploy a digital twin.</blockquote>

<hr>
### Why are Digital Twins important?

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ObGhB9CCHP8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<hr>

### Why should it matter to your organization?

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/o0-N5J6l1nM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
